#+TITLE:[[https://innovate.mygov.in/app-challenge/][ Atmanirbhar Bharat]]

The AatmaNirbhar Bharat App Innovation Challenge is being launched in the following 
8 broad categories 

- [X] Office Productivity & Work from Home
  - Application to provide cloud storage integration, cross-platform file transfer via FTP or LAN, and a root browser on mobile device
  - Mobile application for real-time speech-to-speech translation and camera translation of multiple languages.
  - Application to optimize mobile device's performance by cleaning junk/cache files, optimizing device memory and optimizing battery usage.
  - A robust indigenous anti-virus software for mobile devices.
  - A mobile based photo-editing application with all standard image editing features
    - Application to use mobile devices as image scanners with features like on the fly image correction, image editing, text recognition, etc.
- [X] Social Networking
  - A mobile based microblogging application (meratweet.com)
- [X] E-Learning
  - A mobile based live streaming platform for hosting webinars, lectures, etc.
- [X] Entertainment
  - A mobile based messaging and video calling application
- [X] Health & Wellness
- [X] Business including Agritech and Fintech
  - A mobile application harnessing the most accurate facial and / or body mapping technology to allow for a true-to-life virtual try out of products like spectacles, clothes, etc.
  - An automated web-based application that handles business-to-business lead generation and cold emailing and is completely manageable from a mobile device itself.
  - A mobile application offering satellite imagery and street maps, as well as functions such as a route planner for traveling by foot, car, or with public transportation.
- [X] News
  - A mobile based news application that uses cutting-edge technology to recommend the most relevant and interesting news individually to each use.
- [X] Games
  - A mobile based online gaming platform which also functions as a social hub for gamers



MeraTweet.com
GalvanGhati.com





